# This Dockerfile its used for development, don't release a production image with this
# You must mount a docker volume to src in order to run the image: docker run -v $(pwd)/src:/app/src <image>
FROM node:alpine
WORKDIR "/app"
COPY ./tsconfig.json ./
COPY ./jest.config.js ./
COPY ./package.json ./
RUN yarn install --no-lockfile
CMD ["yarn", "dev"]