version: 2.1
jobs:

  test:
    working_directory: ~/repo
    docker:
    - image: circleci/node:11.4.0
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Dependencies install
        command: yarn install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run:
        name: Test
        command: yarn test

  pushImage:
    working_directory: ~/repo
    docker:
    - image: circleci/node:11.4.0
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Dependencies install
        command: yarn install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run:
        name: Build
        command: yarn build
    - run:
        name: Setup branch name
        command: |
          echo export BRANCH_NAME=${CIRCLE_BRANCH} | tr / - >> $BASH_ENV
    # - run:
    #     name: Setup image name
    #     command: |
    #       echo 'export IMAGE_NAME=submarine' >> $BASH_ENV
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Docker login
        command: |
          docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASS
    - run:
        name: Build and push version image
        command: |
          docker build -t $REGISTRY_NAME/$CIRCLE_PROJECT_REPONAME:$BRANCH_NAME.$CIRCLE_BUILD_NUM .
          docker push $REGISTRY_NAME/$CIRCLE_PROJECT_REPONAME:$BRANCH_NAME.$CIRCLE_BUILD_NUM
    - run:
        name: Build and push latest image
        command: |
          docker build -t $REGISTRY_NAME/$CIRCLE_PROJECT_REPONAME:latest .
          docker push $REGISTRY_NAME/$CIRCLE_PROJECT_REPONAME:latest
    - run:
        name: Create folder workspace
        command: |
          mkdir -p workspace
    - run:
        name: Save image name
        command: |
          echo $REGISTRY_NAME/$CIRCLE_PROJECT_REPONAME:$BRANCH_NAME.$CIRCLE_BUILD_NUM > workspace/image-name
    - persist_to_workspace:
        root: workspace
        paths:
            - image-name

  deployImage:
    working_directory: ~/repo
    docker:
    - image: microsoft/azure-cli:latest
    steps:
    - attach_workspace:
        at: /repo/workspace
    - run:
        name: Setup image name
        command: |
          echo 'export IMAGE_NAME=submarine' >> $BASH_ENV
    - run:
        name: Load image name
        command: |
          echo export IMAGE_NAME=$(cat /repo/workspace/image-name) >> $BASH_ENV
    - run: 
        name: Azure login
        command: az login --service-principal -u $AZURE_SERVICE_PRINCIPAL_USER --password $AZURE_SERVICE_PRINCIPAL_PASS --tenant $AZURE_SERVICE_PRINCIPAL_TENANT
    - run: 
        name: Azure install kubectl
        command: az aks install-cli
    - run: 
        name: Azure get credentials
        command: az aks get-credentials --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_CLUSTER_NAME
    - run:
        name: Update image
        command: kubectl set image deployment/TODO TODO=$IMAGE_NAME
    

workflows:
  version: 2
  workflow:
    jobs:
    - test
    - pushImage:
        requires:
          - test
        filters:
          branches:
            only:
            - dev
            - /release.*/
            - master
            - /hotfix.*/
    - deployImage:
        context: TODO
        requires:
          - test
          - pushImage
        filters:
          branches:
            only:
            - master
            - /hotfix.*/