export const Constants = {
    CONFIG_FILE_PATH: '../../config.json',
    CONFIG_KEY_AZURE_STORAGE_KEY: 'AZURE_STORAGE_KEY',
    CONFIG_KEY_AZURE_STORAGE_CONNECTION_STRING: 'AZURE_STORAGE_CONNECTION_STRING',
    AZURE_STORAGE_ACCOUNT_NAME: 'submarine',
    AZURE_STORAGE_BLOB_CONTAINER_NAME: 'submarine'
};